version: '3'
services:
  # mysql:
  #   image: mysql:latest
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=admin
  #     - MYSQL_DATABASE=admin
  #   network_mode: "host"

  angular-app:
    build:
      context: ./Web/bankclientsrecommender
    ports:
      - "80:80"
  
  spring-app:
    build:
      context: ./Backend/mlopsbackend
    ports:
      - "8080:8080"

  # flask-app:
  #   build:
  #     context: ./MLOpsService/service/src/main/java/com/mlopsservice/ModelScoringService
  #   ports:
  #     - "5000:5000"